# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Gyorgy Kovacs'
tagline:          'Gyorgy Kovacs'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:	   'PhD in Informatics'
url:              https://gykovacs.github.io
baseurl:          /

author:
  name:           'Gyorgy Kovacs'
  url:            https://gykovacs.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gykovacs

#gems: [jekyll-paginate]